# Generated by Django 3.0.7 on 2020-07-20 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsFormEnquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=30)),
                ('email', models.TextField(max_length=100)),
                ('subject', models.TextField(max_length=200)),
                ('message', models.TextField(max_length=500)),
            ],
        ),
    ]
